swagger: "2.0"
paths:
  /api/books:
    post:
      tags:
        - books
      parameters:
        - in: body
          name: new book params
          schema:
            $ref: '#/definitions/Book'
      responses:
        201:
          description: The book has been created
          schema:
            $ref: '#/definitions/Book'
definitions:
  Book:
    properties:
      id:
        type: integer
        readOnly: true
      title:
        type: string
      author:
        type: integer
    required:
      - title
      - author
    type: object
